import { Injectable } from '@angular/core';
import { Symptom, endpoint } from './shared/classes';
import { catchError } from "rxjs/internal/operators";
import { HttpClient, HttpHeaders, HttpErrorResponse } from "@angular/common/http";
import { map } from 'rxjs/operators';
import { Observable, throwError } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SymptomsService {

  //Symptoms are added as static-data to decease DB operation and slight more performance 
  addedSymptoms: Symptom[] = [{ symptom_id: 0, symptom_text: 'abdominal cramp', createdAt: '0', updatedAt: '0' },
  { symptom_id: 1, symptom_text: 'abdominal distention', createdAt: '0', updatedAt: '0' },
  { symptom_id: 2, symptom_text: 'abnormal behavior', createdAt: '0', updatedAt: '0' },
  { symptom_id: 3, symptom_text: 'abnormal bleeding', createdAt: '0', updatedAt: '0' },
  { symptom_id: 4, symptom_text: 'abnormal sensation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 5, symptom_text: 'abnormally frequent', createdAt: '0', updatedAt: '0' },
  { symptom_id: 6, symptom_text: 'abscess', createdAt: '0', updatedAt: '0' },
  { symptom_id: 7, symptom_text: 'aching', createdAt: '0', updatedAt: '0' },
  { symptom_id: 8, symptom_text: 'acne', createdAt: '0', updatedAt: '0' },
  { symptom_id: 9, symptom_text: 'acquiring drinking alcohol taking lot time', createdAt: '0', updatedAt: '0' },
  { symptom_id: 10, symptom_text: 'affected part turning white', createdAt: '0', updatedAt: '0' },
  { symptom_id: 11, symptom_text: 'anemia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 12, symptom_text: 'anxiety', createdAt: '0', updatedAt: '0' },
  { symptom_id: 13, symptom_text: 'arm', createdAt: '0', updatedAt: '0' },
  { symptom_id: 14, symptom_text: 'attack pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 15, symptom_text: 'back', createdAt: '0', updatedAt: '0' },
  { symptom_id: 16, symptom_text: 'bacterial infection', createdAt: '0', updatedAt: '0' },
  { symptom_id: 17, symptom_text: 'bad breath', createdAt: '0', updatedAt: '0' },
  { symptom_id: 18, symptom_text: 'bad smelling thin vaginal discharge', createdAt: '0', updatedAt: '0' },
  { symptom_id: 19, symptom_text: 'bad smelling vaginal discharge', createdAt: '0', updatedAt: '0' },
  { symptom_id: 20, symptom_text: 'barky cough', createdAt: '0', updatedAt: '0' },
  { symptom_id: 21, symptom_text: 'belching', createdAt: '0', updatedAt: '0' },
  { symptom_id: 22, symptom_text: 'better sitting worse lying', createdAt: '0', updatedAt: '0' },
  { symptom_id: 23, symptom_text: 'birth baby younger week gestational age', createdAt: '0', updatedAt: '0' },
  { symptom_id: 24, symptom_text: 'bleeding gum', createdAt: '0', updatedAt: '0' },
  { symptom_id: 25, symptom_text: 'bleeding skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 26, symptom_text: 'blindness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 27, symptom_text: 'blindness one eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 28, symptom_text: 'blister sunlight', createdAt: '0', updatedAt: '0' },
  { symptom_id: 29, symptom_text: 'bloating', createdAt: '0', updatedAt: '0' },
  { symptom_id: 30, symptom_text: 'blood stool', createdAt: '0', updatedAt: '0' },
  { symptom_id: 31, symptom_text: 'blood urine', createdAt: '0', updatedAt: '0' },
  { symptom_id: 32, symptom_text: 'bloody diarrhea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 33, symptom_text: 'blue', createdAt: '0', updatedAt: '0' },
  { symptom_id: 34, symptom_text: 'bluish skin coloration', createdAt: '0', updatedAt: '0' },
  { symptom_id: 35, symptom_text: 'blurred vision', createdAt: '0', updatedAt: '0' },
  { symptom_id: 36, symptom_text: 'blurry vision', createdAt: '0', updatedAt: '0' },
  { symptom_id: 37, symptom_text: 'body tremor', createdAt: '0', updatedAt: '0' },
  { symptom_id: 38, symptom_text: 'bone pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 39, symptom_text: 'bowed leg', createdAt: '0', updatedAt: '0' },
  { symptom_id: 40, symptom_text: 'breakdown skeletal muscle', createdAt: '0', updatedAt: '0' },
  { symptom_id: 41, symptom_text: 'breathing problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 42, symptom_text: 'bruising', createdAt: '0', updatedAt: '0' },
  { symptom_id: 43, symptom_text: 'burning', createdAt: '0', updatedAt: '0' },
  { symptom_id: 44, symptom_text: 'burning redness eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 45, symptom_text: 'burning stabbing pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 46, symptom_text: 'burning urination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 47, symptom_text: 'certain thought repeatedly', createdAt: '0', updatedAt: '0' },
  { symptom_id: 48, symptom_text: 'change bowel movement', createdAt: '0', updatedAt: '0' },
  { symptom_id: 49, symptom_text: 'change breast shape', createdAt: '0', updatedAt: '0' },
  { symptom_id: 50, symptom_text: 'change color', createdAt: '0', updatedAt: '0' },
  { symptom_id: 51, symptom_text: 'change hair', createdAt: '0', updatedAt: '0' },
  { symptom_id: 52, symptom_text: 'change reflex', createdAt: '0', updatedAt: '0' },
  { symptom_id: 53, symptom_text: 'change skin color red black', createdAt: '0', updatedAt: '0' },
  { symptom_id: 54, symptom_text: 'change sleeping eating pattern', createdAt: '0', updatedAt: '0' },
  { symptom_id: 55, symptom_text: 'change taste', createdAt: '0', updatedAt: '0' },
  { symptom_id: 56, symptom_text: 'change voice', createdAt: '0', updatedAt: '0' },
  { symptom_id: 57, symptom_text: 'characteristic facial feature', createdAt: '0', updatedAt: '0' },
  { symptom_id: 58, symptom_text: 'characteristic rash', createdAt: '0', updatedAt: '0' },
  { symptom_id: 59, symptom_text: 'chest discomfort', createdAt: '0', updatedAt: '0' },
  { symptom_id: 60, symptom_text: 'chest pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 61, symptom_text: 'chest tightness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 62, symptom_text: 'chill', createdAt: '0', updatedAt: '0' },
  { symptom_id: 63, symptom_text: 'chronic cough', createdAt: '0', updatedAt: '0' },
  { symptom_id: 64, symptom_text: 'chronic pain bladder', createdAt: '0', updatedAt: '0' },
  { symptom_id: 65, symptom_text: 'clenched fist overlapping finger', createdAt: '0', updatedAt: '0' },
  { symptom_id: 66, symptom_text: 'close object appear blurry', createdAt: '0', updatedAt: '0' },
  { symptom_id: 67, symptom_text: 'clumsy', createdAt: '0', updatedAt: '0' },
  { symptom_id: 68, symptom_text: 'cm lump skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 69, symptom_text: 'cold sweat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 70, symptom_text: 'coma', createdAt: '0', updatedAt: '0' },
  { symptom_id: 71, symptom_text: 'confused thinking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 72, symptom_text: 'confusion', createdAt: '0', updatedAt: '0' },
  { symptom_id: 73, symptom_text: 'constipation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 74, symptom_text: 'coolness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 75, symptom_text: 'coordination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 76, symptom_text: 'cough bloody mucus', createdAt: '0', updatedAt: '0' },
  { symptom_id: 77, symptom_text: 'cough sputum production', createdAt: '0', updatedAt: '0' },
  { symptom_id: 78, symptom_text: 'coughing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 79, symptom_text: 'coughing blood', createdAt: '0', updatedAt: '0' },
  { symptom_id: 80, symptom_text: 'coughing including coughing blood', createdAt: '0', updatedAt: '0' },
  { symptom_id: 81, symptom_text: 'coughing mucus', createdAt: '0', updatedAt: '0' },
  { symptom_id: 82, symptom_text: 'crawl', createdAt: '0', updatedAt: '0' },
  { symptom_id: 83, symptom_text: 'cry episode', createdAt: '0', updatedAt: '0' },
  { symptom_id: 84, symptom_text: 'dark urine', createdAt: '0', updatedAt: '0' },
  { symptom_id: 85, symptom_text: 'darker', createdAt: '0', updatedAt: '0' },
  { symptom_id: 86, symptom_text: 'daytime sleepiness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 87, symptom_text: 'death child le one year age', createdAt: '0', updatedAt: '0' },
  { symptom_id: 88, symptom_text: 'decreased ability feel pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 89, symptom_text: 'decreased ability see', createdAt: '0', updatedAt: '0' },
  { symptom_id: 90, symptom_text: 'decreased ability think', createdAt: '0', updatedAt: '0' },
  { symptom_id: 91, symptom_text: 'decreased ability think remember', createdAt: '0', updatedAt: '0' },
  { symptom_id: 92, symptom_text: 'decreased ability turn', createdAt: '0', updatedAt: '0' },
  { symptom_id: 93, symptom_text: 'decreased appetite', createdAt: '0', updatedAt: '0' },
  { symptom_id: 94, symptom_text: 'decreased motivation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 95, symptom_text: 'decreased range motion', createdAt: '0', updatedAt: '0' },
  { symptom_id: 96, symptom_text: 'decreased taste', createdAt: '0', updatedAt: '0' },
  { symptom_id: 97, symptom_text: 'decreased vision', createdAt: '0', updatedAt: '0' },
  { symptom_id: 98, symptom_text: 'dehydration', createdAt: '0', updatedAt: '0' },
  { symptom_id: 99, symptom_text: 'delayed physical growth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 100, symptom_text: 'delirium', createdAt: '0', updatedAt: '0' },
  { symptom_id: 101, symptom_text: 'delusion', createdAt: '0', updatedAt: '0' },
  { symptom_id: 102, symptom_text: 'dementia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 103, symptom_text: 'depending subtype abdominal pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 104, symptom_text: 'depends organ involved', createdAt: '0', updatedAt: '0' },
  { symptom_id: 105, symptom_text: 'depressed mood', createdAt: '0', updatedAt: '0' },
  { symptom_id: 106, symptom_text: 'depression', createdAt: '0', updatedAt: '0' },
  { symptom_id: 107, symptom_text: 'dermatitis herpetiformis', createdAt: '0', updatedAt: '0' },
  { symptom_id: 108, symptom_text: 'developmental disability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 109, symptom_text: 'diarrhea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 110, symptom_text: 'diarrhea may bloody', createdAt: '0', updatedAt: '0' },
  { symptom_id: 111, symptom_text: 'diarrhea mixed blood', createdAt: '0', updatedAt: '0' },
  { symptom_id: 112, symptom_text: 'diarrhoea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 113, symptom_text: 'difficulty breathing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 114, symptom_text: 'difficulty cutting', createdAt: '0', updatedAt: '0' },
  { symptom_id: 115, symptom_text: 'difficulty eating', createdAt: '0', updatedAt: '0' },
  { symptom_id: 116, symptom_text: 'difficulty getting pregnant', createdAt: '0', updatedAt: '0' },
  { symptom_id: 117, symptom_text: 'difficulty remembering recent event', createdAt: '0', updatedAt: '0' },
  { symptom_id: 118, symptom_text: 'difficulty swallowing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 119, symptom_text: 'difficulty walking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 120, symptom_text: 'dimpling skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 121, symptom_text: 'discharge penis', createdAt: '0', updatedAt: '0' },
  { symptom_id: 122, symptom_text: 'disorientation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 123, symptom_text: 'distant object appear blurry', createdAt: '0', updatedAt: '0' },
  { symptom_id: 124, symptom_text: 'distorted blurred vision distance', createdAt: '0', updatedAt: '0' },
  { symptom_id: 125, symptom_text: 'dizziness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 126, symptom_text: 'double vision', createdAt: '0', updatedAt: '0' },
  { symptom_id: 127, symptom_text: 'drinking large amount alcohol long period', createdAt: '0', updatedAt: '0' },
  { symptom_id: 128, symptom_text: 'drooping eyelid', createdAt: '0', updatedAt: '0' },
  { symptom_id: 129, symptom_text: 'dry cough', createdAt: '0', updatedAt: '0' },
  { symptom_id: 130, symptom_text: 'dry damp skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 131, symptom_text: 'dry eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 132, symptom_text: 'dry mouth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 133, symptom_text: 'ear pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 134, symptom_text: 'easy prolonged bleeding', createdAt: '0', updatedAt: '0' },
  { symptom_id: 135, symptom_text: 'emotional problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 136, symptom_text: 'enlarged lymph node neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 137, symptom_text: 'enlarged spleen', createdAt: '0', updatedAt: '0' },
  { symptom_id: 138, symptom_text: 'enlarged thyroid', createdAt: '0', updatedAt: '0' },
  { symptom_id: 139, symptom_text: 'enlargement thyroid', createdAt: '0', updatedAt: '0' },
  { symptom_id: 140, symptom_text: 'enlargement tonsil', createdAt: '0', updatedAt: '0' },
  { symptom_id: 141, symptom_text: 'episode severe', createdAt: '0', updatedAt: '0' },
  { symptom_id: 142, symptom_text: 'erythema marginatum', createdAt: '0', updatedAt: '0' },
  { symptom_id: 143, symptom_text: 'excess hair', createdAt: '0', updatedAt: '0' },
  { symptom_id: 144, symptom_text: 'excessive amount uterine bleeding', createdAt: '0', updatedAt: '0' },
  { symptom_id: 145, symptom_text: 'excessive daytime sleepiness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 146, symptom_text: 'excessive salivation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 147, symptom_text: 'expanding area redness site tick bite', createdAt: '0', updatedAt: '0' },
  { symptom_id: 148, symptom_text: 'extreme sadness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 149, symptom_text: 'extremity weakness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 150, symptom_text: 'eye pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 151, symptom_text: 'eye strain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 152, symptom_text: 'eyestrain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 153, symptom_text: 'fast heart rate', createdAt: '0', updatedAt: '0' },
  { symptom_id: 154, symptom_text: 'fast heartbeat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 155, symptom_text: 'fatigue', createdAt: '0', updatedAt: '0' },
  { symptom_id: 156, symptom_text: 'fear water', createdAt: '0', updatedAt: '0' },
  { symptom_id: 157, symptom_text: 'feel need check thing repeatedly', createdAt: '0', updatedAt: '0' },
  { symptom_id: 158, symptom_text: 'feeling cold', createdAt: '0', updatedAt: '0' },
  { symptom_id: 159, symptom_text: 'feeling faint upon standing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 160, symptom_text: 'feeling generally unwell', createdAt: '0', updatedAt: '0' },
  { symptom_id: 161, symptom_text: 'feeling like passing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 162, symptom_text: 'feeling need urinate right away', createdAt: '0', updatedAt: '0' },
  { symptom_id: 163, symptom_text: 'feeling tired', createdAt: '0', updatedAt: '0' },
  { symptom_id: 164, symptom_text: 'feeling tired time', createdAt: '0', updatedAt: '0' },
  { symptom_id: 165, symptom_text: 'fever', createdAt: '0', updatedAt: '0' },
  { symptom_id: 166, symptom_text: 'firm', createdAt: '0', updatedAt: '0' },
  { symptom_id: 167, symptom_text: 'flat discolored spot bump may blister', createdAt: '0', updatedAt: '0' },
  { symptom_id: 168, symptom_text: 'flu like illness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 169, symptom_text: 'flu like symptom', createdAt: '0', updatedAt: '0' },
  { symptom_id: 170, symptom_text: 'fluid filled blister scab', createdAt: '0', updatedAt: '0' },
  { symptom_id: 171, symptom_text: 'fluid nipple', createdAt: '0', updatedAt: '0' },
  { symptom_id: 172, symptom_text: 'frequent infection', createdAt: '0', updatedAt: '0' },
  { symptom_id: 173, symptom_text: 'frequent urination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 174, symptom_text: 'fullness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 175, symptom_text: 'gas', createdAt: '0', updatedAt: '0' },
  { symptom_id: 176, symptom_text: 'gradual loss coordination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 177, symptom_text: 'growth delay', createdAt: '0', updatedAt: '0' },
  { symptom_id: 178, symptom_text: 'gum disease', createdAt: '0', updatedAt: '0' },
  { symptom_id: 179, symptom_text: 'hair loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 180, symptom_text: 'half ring finger', createdAt: '0', updatedAt: '0' },
  { symptom_id: 181, symptom_text: 'hallucination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 182, symptom_text: 'hallucination usually hearing voice', createdAt: '0', updatedAt: '0' },
  { symptom_id: 183, symptom_text: 'hard swelling skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 184, symptom_text: 'hard time reading small print', createdAt: '0', updatedAt: '0' },
  { symptom_id: 185, symptom_text: 'headache', createdAt: '0', updatedAt: '0' },
  { symptom_id: 186, symptom_text: 'hearing loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 187, symptom_text: 'hearing sound external sound present', createdAt: '0', updatedAt: '0' },
  { symptom_id: 188, symptom_text: 'heartburn', createdAt: '0', updatedAt: '0' },
  { symptom_id: 189, symptom_text: 'heat intolerance', createdAt: '0', updatedAt: '0' },
  { symptom_id: 190, symptom_text: 'heavy period', createdAt: '0', updatedAt: '0' },
  { symptom_id: 191, symptom_text: 'high blood pressure', createdAt: '0', updatedAt: '0' },
  { symptom_id: 192, symptom_text: 'high body temperature', createdAt: '0', updatedAt: '0' },
  { symptom_id: 193, symptom_text: 'hoarse voice', createdAt: '0', updatedAt: '0' },
  { symptom_id: 194, symptom_text: 'hold reading material farther away', createdAt: '0', updatedAt: '0' },
  { symptom_id: 195, symptom_text: 'impaired communication', createdAt: '0', updatedAt: '0' },
  { symptom_id: 196, symptom_text: 'inability child', createdAt: '0', updatedAt: '0' },
  { symptom_id: 197, symptom_text: 'inability move facial muscle one side', createdAt: '0', updatedAt: '0' },
  { symptom_id: 198, symptom_text: 'inability move feel one side body', createdAt: '0', updatedAt: '0' },
  { symptom_id: 199, symptom_text: 'increased breath rate', createdAt: '0', updatedAt: '0' },
  { symptom_id: 200, symptom_text: 'increased breathing rate', createdAt: '0', updatedAt: '0' },
  { symptom_id: 201, symptom_text: 'increased fat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 202, symptom_text: 'increased heart rate', createdAt: '0', updatedAt: '0' },
  { symptom_id: 203, symptom_text: 'increased hunger', createdAt: '0', updatedAt: '0' },
  { symptom_id: 204, symptom_text: 'increased risk broken bone', createdAt: '0', updatedAt: '0' },
  { symptom_id: 205, symptom_text: 'increased risk infection', createdAt: '0', updatedAt: '0' },
  { symptom_id: 206, symptom_text: 'increased thirst', createdAt: '0', updatedAt: '0' },
  { symptom_id: 207, symptom_text: 'increasing weakening', createdAt: '0', updatedAt: '0' },
  { symptom_id: 208, symptom_text: 'index', createdAt: '0', updatedAt: '0' },
  { symptom_id: 209, symptom_text: 'infertility', createdAt: '0', updatedAt: '0' },
  { symptom_id: 210, symptom_text: 'inflamed eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 211, symptom_text: 'insomnia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 212, symptom_text: 'intellectual disability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 213, symptom_text: 'involuntary muscle movement', createdAt: '0', updatedAt: '0' },
  { symptom_id: 214, symptom_text: 'involuntary sleep episode', createdAt: '0', updatedAt: '0' },
  { symptom_id: 215, symptom_text: 'irregular edge', createdAt: '0', updatedAt: '0' },
  { symptom_id: 216, symptom_text: 'irregular menstrual period', createdAt: '0', updatedAt: '0' },
  { symptom_id: 217, symptom_text: 'irregular menstruation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 218, symptom_text: 'irritability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 219, symptom_text: 'irritation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 220, symptom_text: 'itchiness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 221, symptom_text: 'itching', createdAt: '0', updatedAt: '0' },
  { symptom_id: 222, symptom_text: 'itching genital area', createdAt: '0', updatedAt: '0' },
  { symptom_id: 223, symptom_text: 'itching result trouble sleeping', createdAt: '0', updatedAt: '0' },
  { symptom_id: 224, symptom_text: 'itchy', createdAt: '0', updatedAt: '0' },
  { symptom_id: 225, symptom_text: 'itchy blister', createdAt: '0', updatedAt: '0' },
  { symptom_id: 226, symptom_text: 'itchy bump', createdAt: '0', updatedAt: '0' },
  { symptom_id: 227, symptom_text: 'itchy ear', createdAt: '0', updatedAt: '0' },
  { symptom_id: 228, symptom_text: 'jaundice', createdAt: '0', updatedAt: '0' },
  { symptom_id: 229, symptom_text: 'jaw', createdAt: '0', updatedAt: '0' },
  { symptom_id: 230, symptom_text: 'jerky body movement', createdAt: '0', updatedAt: '0' },
  { symptom_id: 231, symptom_text: 'joint bone pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 232, symptom_text: 'joint swelling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 233, symptom_text: 'large amount watery diarrhea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 234, symptom_text: 'large forehead', createdAt: '0', updatedAt: '0' },
  { symptom_id: 235, symptom_text: 'large lymph node', createdAt: '0', updatedAt: '0' },
  { symptom_id: 236, symptom_text: 'large lymph node around neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 237, symptom_text: 'leg swelling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 238, symptom_text: 'light sensitivity', createdAt: '0', updatedAt: '0' },
  { symptom_id: 239, symptom_text: 'little pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 240, symptom_text: 'localized breast pain redness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 241, symptom_text: 'long term fatigue', createdAt: '0', updatedAt: '0' },
  { symptom_id: 242, symptom_text: 'loose frequent bowel movement', createdAt: '0', updatedAt: '0' },
  { symptom_id: 243, symptom_text: 'loose teeth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 244, symptom_text: 'loss appetite', createdAt: '0', updatedAt: '0' },
  { symptom_id: 245, symptom_text: 'loss consciousness may sweating', createdAt: '0', updatedAt: '0' },
  { symptom_id: 246, symptom_text: 'loss hair part head body', createdAt: '0', updatedAt: '0' },
  { symptom_id: 247, symptom_text: 'loss lot blood childbirth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 248, symptom_text: 'loss smell', createdAt: '0', updatedAt: '0' },
  { symptom_id: 249, symptom_text: 'loss vision one side', createdAt: '0', updatedAt: '0' },
  { symptom_id: 250, symptom_text: 'low blood pressure', createdAt: '0', updatedAt: '0' },
  { symptom_id: 251, symptom_text: 'low energy', createdAt: '0', updatedAt: '0' },
  { symptom_id: 252, symptom_text: 'low red blood cell', createdAt: '0', updatedAt: '0' },
  { symptom_id: 253, symptom_text: 'lower abdominal pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 254, symptom_text: 'lump breast', createdAt: '0', updatedAt: '0' },
  { symptom_id: 255, symptom_text: 'lump bump neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 256, symptom_text: 'maculopapular rash', createdAt: '0', updatedAt: '0' },
  { symptom_id: 257, symptom_text: 'malabsorption', createdAt: '0', updatedAt: '0' },
  { symptom_id: 258, symptom_text: 'may symptom', createdAt: '0', updatedAt: '0' },
  { symptom_id: 259, symptom_text: 'memory problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 260, symptom_text: 'mental ability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 261, symptom_text: 'mental change', createdAt: '0', updatedAt: '0' },
  { symptom_id: 262, symptom_text: 'mid dilated pupil', createdAt: '0', updatedAt: '0' },
  { symptom_id: 263, symptom_text: 'middle finger', createdAt: '0', updatedAt: '0' },
  { symptom_id: 264, symptom_text: 'mild moderate intellectual disability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 265, symptom_text: 'minimal', createdAt: '0', updatedAt: '0' },
  { symptom_id: 266, symptom_text: 'missed period', createdAt: '0', updatedAt: '0' },
  { symptom_id: 267, symptom_text: 'mole increasing size', createdAt: '0', updatedAt: '0' },
  { symptom_id: 268, symptom_text: 'mood change', createdAt: '0', updatedAt: '0' },
  { symptom_id: 269, symptom_text: 'mood swing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 270, symptom_text: 'mouth sore', createdAt: '0', updatedAt: '0' },
  { symptom_id: 271, symptom_text: 'mouth ulcer', createdAt: '0', updatedAt: '0' },
  { symptom_id: 272, symptom_text: 'multiple painful joint', createdAt: '0', updatedAt: '0' },
  { symptom_id: 273, symptom_text: 'muscle ache difficulty breathing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 274, symptom_text: 'muscle cramp', createdAt: '0', updatedAt: '0' },
  { symptom_id: 275, symptom_text: 'muscle joint pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 276, symptom_text: 'muscle spasm', createdAt: '0', updatedAt: '0' },
  { symptom_id: 277, symptom_text: 'muscle weakness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 278, symptom_text: 'muscle weakness beginning foot hand', createdAt: '0', updatedAt: '0' },
  { symptom_id: 279, symptom_text: 'muscle weakness resulting inability move', createdAt: '0', updatedAt: '0' },
  { symptom_id: 280, symptom_text: 'muscular pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 281, symptom_text: 'myalgia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 282, symptom_text: 'nausea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 283, symptom_text: 'nausea vomiting', createdAt: '0', updatedAt: '0' },
  { symptom_id: 284, symptom_text: 'nausea vomiting weight loss dehydration occur', createdAt: '0', updatedAt: '0' },
  { symptom_id: 285, symptom_text: 'nearly undetectable spell', createdAt: '0', updatedAt: '0' },
  { symptom_id: 286, symptom_text: 'nearsightedness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 287, symptom_text: 'neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 288, symptom_text: 'neck stiffness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 289, symptom_text: 'needing urinate often', createdAt: '0', updatedAt: '0' },
  { symptom_id: 290, symptom_text: 'newly inverted nipple', createdAt: '0', updatedAt: '0' },
  { symptom_id: 291, symptom_text: 'non itchy skin ulcer', createdAt: '0', updatedAt: '0' },
  { symptom_id: 292, symptom_text: 'non painful cyst middle eyelid', createdAt: '0', updatedAt: '0' },
  { symptom_id: 293, symptom_text: 'nonaligned eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 294, symptom_text: 'none non specific', createdAt: '0', updatedAt: '0' },
  { symptom_id: 295, symptom_text: 'numbness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 296, symptom_text: 'object different size eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 297, symptom_text: 'one eye myopia eye hyperopia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 298, symptom_text: 'opening upper lip may extend nose palate', createdAt: '0', updatedAt: '0' },
  { symptom_id: 299, symptom_text: 'others', createdAt: '0', updatedAt: '0' },
  { symptom_id: 300, symptom_text: 'overlying redness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 301, symptom_text: 'pain along inside edge shinbone', createdAt: '0', updatedAt: '0' },
  { symptom_id: 302, symptom_text: 'pain area', createdAt: '0', updatedAt: '0' },
  { symptom_id: 303, symptom_text: 'pain around ear', createdAt: '0', updatedAt: '0' },
  { symptom_id: 304, symptom_text: 'pain doesnt go shingle', createdAt: '0', updatedAt: '0' },
  { symptom_id: 305, symptom_text: 'pain going leg lower back', createdAt: '0', updatedAt: '0' },
  { symptom_id: 306, symptom_text: 'pain sex', createdAt: '0', updatedAt: '0' },
  { symptom_id: 307, symptom_text: 'pain specific bone', createdAt: '0', updatedAt: '0' },
  { symptom_id: 308, symptom_text: 'painful', createdAt: '0', updatedAt: '0' },
  { symptom_id: 309, symptom_text: 'painful blister lower leg', createdAt: '0', updatedAt: '0' },
  { symptom_id: 310, symptom_text: 'painful heavy period', createdAt: '0', updatedAt: '0' },
  { symptom_id: 311, symptom_text: 'painful joint base big toe', createdAt: '0', updatedAt: '0' },
  { symptom_id: 312, symptom_text: 'painful rash occurring stripe', createdAt: '0', updatedAt: '0' },
  { symptom_id: 313, symptom_text: 'painful skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 314, symptom_text: 'painful swelling parotid gland', createdAt: '0', updatedAt: '0' },
  { symptom_id: 315, symptom_text: 'painful swollen joint', createdAt: '0', updatedAt: '0' },
  { symptom_id: 316, symptom_text: 'painful tender outer part elbow', createdAt: '0', updatedAt: '0' },
  { symptom_id: 317, symptom_text: 'painless', createdAt: '0', updatedAt: '0' },
  { symptom_id: 318, symptom_text: 'painless lump', createdAt: '0', updatedAt: '0' },
  { symptom_id: 319, symptom_text: 'pale color', createdAt: '0', updatedAt: '0' },
  { symptom_id: 320, symptom_text: 'pale skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 321, symptom_text: 'pallor', createdAt: '0', updatedAt: '0' },
  { symptom_id: 322, symptom_text: 'paralysis', createdAt: '0', updatedAt: '0' },
  { symptom_id: 323, symptom_text: 'patch thick', createdAt: '0', updatedAt: '0' },
  { symptom_id: 324, symptom_text: 'patch white skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 325, symptom_text: 'perform certain routine repeatedly', createdAt: '0', updatedAt: '0' },
  { symptom_id: 326, symptom_text: 'period vigorous shaking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 327, symptom_text: 'persistent rough white red patch mouth lasting longer week', createdAt: '0', updatedAt: '0' },
  { symptom_id: 328, symptom_text: 'photophobia', createdAt: '0', updatedAt: '0' },
  { symptom_id: 329, symptom_text: 'physical disability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 330, symptom_text: 'pimple like rash', createdAt: '0', updatedAt: '0' },
  { symptom_id: 331, symptom_text: 'pinkish', createdAt: '0', updatedAt: '0' },
  { symptom_id: 332, symptom_text: 'playing video game extremely long period time', createdAt: '0', updatedAt: '0' },
  { symptom_id: 333, symptom_text: 'poor ability tolerate cold', createdAt: '0', updatedAt: '0' },
  { symptom_id: 334, symptom_text: 'poor appetite', createdAt: '0', updatedAt: '0' },
  { symptom_id: 335, symptom_text: 'poor coordination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 336, symptom_text: 'poor tolerance heat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 337, symptom_text: 'post nasal drip', createdAt: '0', updatedAt: '0' },
  { symptom_id: 338, symptom_text: 'problem language', createdAt: '0', updatedAt: '0' },
  { symptom_id: 339, symptom_text: 'problem mood', createdAt: '0', updatedAt: '0' },
  { symptom_id: 340, symptom_text: 'problem understanding speaking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 341, symptom_text: 'problem vision', createdAt: '0', updatedAt: '0' },
  { symptom_id: 342, symptom_text: 'profuse sweating', createdAt: '0', updatedAt: '0' },
  { symptom_id: 343, symptom_text: 'progressive muscle weakness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 344, symptom_text: 'prolonged', createdAt: '0', updatedAt: '0' },
  { symptom_id: 345, symptom_text: 'prolonged cough', createdAt: '0', updatedAt: '0' },
  { symptom_id: 346, symptom_text: 'prominent', createdAt: '0', updatedAt: '0' },
  { symptom_id: 347, symptom_text: 'protein urine', createdAt: '0', updatedAt: '0' },
  { symptom_id: 348, symptom_text: 'psychosis', createdAt: '0', updatedAt: '0' },
  { symptom_id: 349, symptom_text: 'pulsing pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 350, symptom_text: 'purple colored skin affected area', createdAt: '0', updatedAt: '0' },
  { symptom_id: 351, symptom_text: 'purple colored skin lesion', createdAt: '0', updatedAt: '0' },
  { symptom_id: 352, symptom_text: 'raised', createdAt: '0', updatedAt: '0' },
  { symptom_id: 353, symptom_text: 'raised red blue lesion', createdAt: '0', updatedAt: '0' },
  { symptom_id: 354, symptom_text: 'random outburst laughter', createdAt: '0', updatedAt: '0' },
  { symptom_id: 355, symptom_text: 'rapid breathing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 356, symptom_text: 'recurring episode wheezing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 357, symptom_text: 'red', createdAt: '0', updatedAt: '0' },
  { symptom_id: 358, symptom_text: 'red eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 359, symptom_text: 'red purple darker skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 360, symptom_text: 'red rash', createdAt: '0', updatedAt: '0' },
  { symptom_id: 361, symptom_text: 'red scaly patch skin breast', createdAt: '0', updatedAt: '0' },
  { symptom_id: 362, symptom_text: 'red skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 363, symptom_text: 'red spot white eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 364, symptom_text: 'red without blister', createdAt: '0', updatedAt: '0' },
  { symptom_id: 365, symptom_text: 'reddish eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 366, symptom_text: 'redness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 367, symptom_text: 'redness eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 368, symptom_text: 'repetitive behavior', createdAt: '0', updatedAt: '0' },
  { symptom_id: 369, symptom_text: 'restricted interest', createdAt: '0', updatedAt: '0' },
  { symptom_id: 370, symptom_text: 'right lower abdominal pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 371, symptom_text: 'rigidity', createdAt: '0', updatedAt: '0' },
  { symptom_id: 372, symptom_text: 'ringing ear heartbeat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 373, symptom_text: 'rough skin growth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 374, symptom_text: 'runny nose', createdAt: '0', updatedAt: '0' },
  { symptom_id: 375, symptom_text: 'scaly patch skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 376, symptom_text: 'scratchiness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 377, symptom_text: 'seizure', createdAt: '0', updatedAt: '0' },
  { symptom_id: 378, symptom_text: 'sensitivity smell', createdAt: '0', updatedAt: '0' },
  { symptom_id: 379, symptom_text: 'sensitivity sound', createdAt: '0', updatedAt: '0' },
  { symptom_id: 380, symptom_text: 'severe intellectual disability', createdAt: '0', updatedAt: '0' },
  { symptom_id: 381, symptom_text: 'severe pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 382, symptom_text: 'severe pain lower back abdomen', createdAt: '0', updatedAt: '0' },
  { symptom_id: 383, symptom_text: 'shakiness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 384, symptom_text: 'shaking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 385, symptom_text: 'sharp chest pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 386, symptom_text: 'shivering', createdAt: '0', updatedAt: '0' },
  { symptom_id: 387, symptom_text: 'shock like pain one side face last second minute', createdAt: '0', updatedAt: '0' },
  { symptom_id: 388, symptom_text: 'short height', createdAt: '0', updatedAt: '0' },
  { symptom_id: 389, symptom_text: 'short stature', createdAt: '0', updatedAt: '0' },
  { symptom_id: 390, symptom_text: 'shortness breath', createdAt: '0', updatedAt: '0' },
  { symptom_id: 391, symptom_text: 'sit', createdAt: '0', updatedAt: '0' },
  { symptom_id: 392, symptom_text: 'skin blister', createdAt: '0', updatedAt: '0' },
  { symptom_id: 393, symptom_text: 'skin breakdown', createdAt: '0', updatedAt: '0' },
  { symptom_id: 394, symptom_text: 'skin lesion generally pink color project outward', createdAt: '0', updatedAt: '0' },
  { symptom_id: 395, symptom_text: 'skin peeling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 396, symptom_text: 'sleep problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 397, symptom_text: 'sleeping problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 398, symptom_text: 'slowness movement', createdAt: '0', updatedAt: '0' },
  { symptom_id: 399, symptom_text: 'small', createdAt: '0', updatedAt: '0' },
  { symptom_id: 400, symptom_text: 'small blister break open form painful ulcer', createdAt: '0', updatedAt: '0' },
  { symptom_id: 401, symptom_text: 'small blister surrounding swelling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 402, symptom_text: 'small face', createdAt: '0', updatedAt: '0' },
  { symptom_id: 403, symptom_text: 'small head', createdAt: '0', updatedAt: '0' },
  { symptom_id: 404, symptom_text: 'small jaw', createdAt: '0', updatedAt: '0' },
  { symptom_id: 405, symptom_text: 'sneezing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 406, symptom_text: 'social withdrawal', createdAt: '0', updatedAt: '0' },
  { symptom_id: 407, symptom_text: 'sometimes symptom', createdAt: '0', updatedAt: '0' },
  { symptom_id: 408, symptom_text: 'sore arm leg', createdAt: '0', updatedAt: '0' },
  { symptom_id: 409, symptom_text: 'sore throat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 410, symptom_text: 'sore wrist', createdAt: '0', updatedAt: '0' },
  { symptom_id: 411, symptom_text: 'stiff muscle', createdAt: '0', updatedAt: '0' },
  { symptom_id: 412, symptom_text: 'stiff neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 413, symptom_text: 'stiffness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 414, symptom_text: 'stomach pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 415, symptom_text: 'stroke', createdAt: '0', updatedAt: '0' },
  { symptom_id: 416, symptom_text: 'stuffy itchy nose', createdAt: '0', updatedAt: '0' },
  { symptom_id: 417, symptom_text: 'stunted growth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 418, symptom_text: 'sudden', createdAt: '0', updatedAt: '0' },
  { symptom_id: 419, symptom_text: 'sudden loss muscle strength', createdAt: '0', updatedAt: '0' },
  { symptom_id: 420, symptom_text: 'sweat', createdAt: '0', updatedAt: '0' },
  { symptom_id: 421, symptom_text: 'swell pain near tumor', createdAt: '0', updatedAt: '0' },
  { symptom_id: 422, symptom_text: 'swelling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 423, symptom_text: 'swelling abdomen', createdAt: '0', updatedAt: '0' },
  { symptom_id: 424, symptom_text: 'swelling around eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 425, symptom_text: 'swelling hand foot', createdAt: '0', updatedAt: '0' },
  { symptom_id: 426, symptom_text: 'swollen', createdAt: '0', updatedAt: '0' },
  { symptom_id: 427, symptom_text: 'swollen hand foot', createdAt: '0', updatedAt: '0' },
  { symptom_id: 428, symptom_text: 'swollen lymph node', createdAt: '0', updatedAt: '0' },
  { symptom_id: 429, symptom_text: 'taste acid', createdAt: '0', updatedAt: '0' },
  { symptom_id: 430, symptom_text: 'temporary fleeting vision one eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 431, symptom_text: 'tender breast', createdAt: '0', updatedAt: '0' },
  { symptom_id: 432, symptom_text: 'testicular pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 433, symptom_text: 'tingling', createdAt: '0', updatedAt: '0' },
  { symptom_id: 434, symptom_text: 'tingling hand foot', createdAt: '0', updatedAt: '0' },
  { symptom_id: 435, symptom_text: 'tingling thumb', createdAt: '0', updatedAt: '0' },
  { symptom_id: 436, symptom_text: 'tiredness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 437, symptom_text: 'tooth loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 438, symptom_text: 'tremor', createdAt: '0', updatedAt: '0' },
  { symptom_id: 439, symptom_text: 'triangular tissue growth cornea', createdAt: '0', updatedAt: '0' },
  { symptom_id: 440, symptom_text: 'trouble breathing nose', createdAt: '0', updatedAt: '0' },
  { symptom_id: 441, symptom_text: 'trouble coordination', createdAt: '0', updatedAt: '0' },
  { symptom_id: 442, symptom_text: 'trouble opening mouth', createdAt: '0', updatedAt: '0' },
  { symptom_id: 443, symptom_text: 'trouble seeing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 444, symptom_text: 'trouble sensation', createdAt: '0', updatedAt: '0' },
  { symptom_id: 445, symptom_text: 'trouble sleeping', createdAt: '0', updatedAt: '0' },
  { symptom_id: 446, symptom_text: 'trouble social interaction', createdAt: '0', updatedAt: '0' },
  { symptom_id: 447, symptom_text: 'trouble speaking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 448, symptom_text: 'trouble swallowing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 449, symptom_text: 'trouble talking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 450, symptom_text: 'trouble walking', createdAt: '0', updatedAt: '0' },
  { symptom_id: 451, symptom_text: 'typically none', createdAt: '0', updatedAt: '0' },
  { symptom_id: 452, symptom_text: 'ulcer', createdAt: '0', updatedAt: '0' },
  { symptom_id: 453, symptom_text: 'ulcer around genitals', createdAt: '0', updatedAt: '0' },
  { symptom_id: 454, symptom_text: 'ulceration', createdAt: '0', updatedAt: '0' },
  { symptom_id: 455, symptom_text: 'unable move', createdAt: '0', updatedAt: '0' },
  { symptom_id: 456, symptom_text: 'unexplained weight loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 457, symptom_text: 'unintended weight loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 458, symptom_text: 'unpleasant smell present breath', createdAt: '0', updatedAt: '0' },
  { symptom_id: 459, symptom_text: 'upper abdominal pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 460, symptom_text: 'usage resulting problem', createdAt: '0', updatedAt: '0' },
  { symptom_id: 461, symptom_text: 'vaginal bleeding', createdAt: '0', updatedAt: '0' },
  { symptom_id: 462, symptom_text: 'vaginal bleeding without pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 463, symptom_text: 'vaginal discharge', createdAt: '0', updatedAt: '0' },
  { symptom_id: 464, symptom_text: 'variable', createdAt: '0', updatedAt: '0' },
  { symptom_id: 465, symptom_text: 'vary depending part brain involved', createdAt: '0', updatedAt: '0' },
  { symptom_id: 466, symptom_text: 'varying degree muscle weakness', createdAt: '0', updatedAt: '0' },
  { symptom_id: 467, symptom_text: 'velvety skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 468, symptom_text: 'vision loss', createdAt: '0', updatedAt: '0' },
  { symptom_id: 469, symptom_text: 'vomiting', createdAt: '0', updatedAt: '0' },
  { symptom_id: 470, symptom_text: 'warm', createdAt: '0', updatedAt: '0' },
  { symptom_id: 471, symptom_text: 'wart', createdAt: '0', updatedAt: '0' },
  { symptom_id: 472, symptom_text: 'watery eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 473, symptom_text: 'weak grip', createdAt: '0', updatedAt: '0' },
  { symptom_id: 474, symptom_text: 'weak muscle', createdAt: '0', updatedAt: '0' },
  { symptom_id: 475, symptom_text: 'weakness limb', createdAt: '0', updatedAt: '0' },
  { symptom_id: 476, symptom_text: 'weakness numbness affected leg', createdAt: '0', updatedAt: '0' },
  { symptom_id: 477, symptom_text: 'webbed neck', createdAt: '0', updatedAt: '0' },
  { symptom_id: 478, symptom_text: 'weight gain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 479, symptom_text: 'wet', createdAt: '0', updatedAt: '0' },
  { symptom_id: 480, symptom_text: 'wheezing', createdAt: '0', updatedAt: '0' },
  { symptom_id: 481, symptom_text: 'white patch vaginal discharge', createdAt: '0', updatedAt: '0' },
  { symptom_id: 482, symptom_text: 'widespread pain', createdAt: '0', updatedAt: '0' },
  { symptom_id: 483, symptom_text: 'withdrawal occurring stopping', createdAt: '0', updatedAt: '0' },
  { symptom_id: 484, symptom_text: 'worrying', createdAt: '0', updatedAt: '0' },
  { symptom_id: 485, symptom_text: 'yellow skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 486, symptom_text: 'yellowish coloration skin white eye', createdAt: '0', updatedAt: '0' },
  { symptom_id: 487, symptom_text: 'yellowish skin', createdAt: '0', updatedAt: '0' },
  { symptom_id: 488, symptom_text: 'yellowish skin crust', createdAt: '0', updatedAt: '0' }];

  private extractData(res: Response): any {
    const body = res;
    return body || {};
  }

  constructor(private http: HttpClient) {
  }

  getSymptoms(): Observable<any> {
    return this.http.get(endpoint + 'symptoms/').pipe
      (map(this.extractData),
        catchError(this.handleError));
  }

  private handleError(error: HttpErrorResponse): any {
    if (error.error instanceof ErrorEvent) {
      console.error('An error occurred', error.error.message)
    }
    else {
      console.error(
        'Backend returned code  ' + error.status +
        'body was: ' + error.message
      );
    }
    return throwError(
      ('Something bad happened; please try again later!')
    )
  }



}
